import { Rate } from '../types/rate';

/** Default 2026 rates — used as fallback when API is unavailable */
export const DEFAULT_RATES: Rate[] = [
  { id: '', slug: 'vin_tranquille', label: 'Vin tranquille', examples: 'Vins rouges, blancs, roses non effervescents — Bordeaux, Bourgogne, Cotes-du-Rhone...', calcType: 'A', acciseRate: 4.19, acciseUnit: 'euro/hl', cotisationRate: 0, cotisationUnit: null, cotisationCond: null, sortOrder: 1, updatedAt: '' },
  { id: '', slug: 'vin_mousseux', label: 'Vin mousseux', examples: 'Vins effervescents — Champagne, Cremant, Prosecco, Cava, mousseux', calcType: 'A', acciseRate: 10.38, acciseUnit: 'euro/hl', cotisationRate: 0, cotisationUnit: null, cotisationCond: null, sortOrder: 2, updatedAt: '' },
  { id: '', slug: 'cidre_poire', label: 'Cidre / Poire', examples: 'Cidre brut, demi-sec, doux, poire, hydromel — tarif reduit', calcType: 'A', acciseRate: 1.46, acciseUnit: 'euro/hl', cotisationRate: 0, cotisationUnit: null, cotisationCond: null, sortOrder: 3, updatedAt: '' },
  { id: '', slug: 'boisson_fermentee', label: 'Autre boisson fermentee', examples: 'Boissons fermentees hors vin/biere — Kombucha alcoolise, sake, kefir, hydromel', calcType: 'A', acciseRate: 4.19, acciseUnit: 'euro/hl', cotisationRate: 0, cotisationUnit: null, cotisationCond: null, sortOrder: 4, updatedAt: '' },
  { id: '', slug: 'prod_interm_vdl_vdn', label: 'Porto / VDN / VDL', examples: 'Vins doux naturels et de liqueur — Porto, Banyuls, Muscat, Rivesaltes (tarif reduit)', calcType: 'A', acciseRate: 52.39, acciseUnit: 'euro/hl', cotisationRate: 20.97, cotisationUnit: 'euro/hl', cotisationCond: '>18', sortOrder: 5, updatedAt: '' },
  { id: '', slug: 'prod_interm_autre', label: 'Vermouth / Aperitif vine', examples: 'Produits intermediaires a base de vin — Vermouth, Lillet, Byrrh, Pineau des Charentes', calcType: 'A', acciseRate: 209.53, acciseUnit: 'euro/hl', cotisationRate: 52.39, cotisationUnit: 'euro/hl', cotisationCond: '>18', sortOrder: 6, updatedAt: '' },
  { id: '', slug: 'biere_legere', label: 'Biere legere (0,5% a 2,8%)', examples: 'Panaches, bieres sans alcool, radlers — jusqu\'a 2,8% vol.', calcType: 'B', acciseRate: 4.12, acciseUnit: 'euro/hl_degree', cotisationRate: 52.39, cotisationUnit: 'euro/hl', cotisationCond: '>18', sortOrder: 7, updatedAt: '' },
  { id: '', slug: 'biere', label: 'Biere (plus de 2,8%)', examples: 'IPA, lagers, stouts, blondes, ambrees — au-dessus de 2,8% vol.', calcType: 'B', acciseRate: 8.24, acciseUnit: 'euro/hl_degree', cotisationRate: 52.39, cotisationUnit: 'euro/hl', cotisationCond: '>18', sortOrder: 8, updatedAt: '' },
  { id: '', slug: 'petite_brasserie', label: 'Biere artisanale (petite brasserie)', examples: 'Micro-brasseries, brasseries craft — production max 200 000 hl/an, tarif reduit', calcType: 'B', acciseRate: 4.12, acciseUnit: 'euro/hl_degree', cotisationRate: 52.39, cotisationUnit: 'euro/hl', cotisationCond: '>18', sortOrder: 9, updatedAt: '' },
  { id: '', slug: 'rhum_dom', label: 'Rhum des DOM', examples: 'Rhum produit outre-mer (Martinique, Guadeloupe, Reunion) — tarif reduit de moitie', calcType: 'C', acciseRate: 966.75, acciseUnit: 'euro/hlap', cotisationRate: 620.47, cotisationUnit: 'euro/hlap', cotisationCond: '>18', sortOrder: 10, updatedAt: '' },
  { id: '', slug: 'liqueur', label: 'Liqueur', examples: 'Liqueurs, cremes de fruits, elixirs, amaretto, limoncello, Chartreuse...', calcType: 'C', acciseRate: 1932.42, acciseUnit: 'euro/hlap', cotisationRate: 620.47, cotisationUnit: 'euro/hlap', cotisationCond: '>18', sortOrder: 11, updatedAt: '' },
  { id: '', slug: 'spiritueux', label: 'Spiritueux', examples: 'Alcools forts distilles — Whisky, vodka, gin, cognac, armagnac, tequila, mezcal...', calcType: 'C', acciseRate: 1932.42, acciseUnit: 'euro/hlap', cotisationRate: 620.47, cotisationUnit: 'euro/hlap', cotisationCond: '>18', sortOrder: 12, updatedAt: '' },
  { id: '', slug: 'rhum_hors_dom', label: 'Rhum (hors DOM)', examples: 'Rhum d\'importation — cubain, jamaicain, venezuelien, philippin (tarif plein)', calcType: 'C', acciseRate: 1932.42, acciseUnit: 'euro/hlap', cotisationRate: 620.47, cotisationUnit: 'euro/hlap', cotisationCond: '>18', sortOrder: 13, updatedAt: '' },
];
